version: "3"

# Docker Comose file for Directus instance §§label§§ (§§name§§)

services:
  directus_§§label§§_db_§§instanceCounter§§:
    container_name: directus_§§label§§_db_§§instanceCounter§§
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - §§portCounter3306§§:3306
    volumes:
      - directus_db_§§instanceCounter§§:/var/lib/mysql
    networks:
      - directus_§§label§§_network_§§instanceCounter§§
    environment:
      MARIADB_ROOT_PASSWORD: §§pwRoot§§
      MARIADB_USER: directus
      MARIADB_PASSWORD: §§pwMariaDB§§
      MARIADB_DATABASE: directus
  directus_pma_§§instanceCounter§§:
    container_name: directus_§§label§§_pma_§§instanceCounter§§
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - §§portCounter80§§:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=directus_§§label§§_db_§§instanceCounter§§
      - PMA_PORT=3306
      # - PMA_ABSOLUTE_URI=§§url§§/phpmyadmin/
    networks:
      - directus_§§label§§_network_§§instanceCounter§§
  # directus_cache_§§instanceCounter§§:
  #   container_name: directus_§§label§§_cache_§§instanceCounter§§
  #   image: redis:latest
  #   restart: unless-stopped
  #   networks:
  #     - directus_§§label§§_network_§§instanceCounter§§
  directus_§§label§§_§§instanceCounter§§:
    container_name: directus_§§label§§_§§instanceCounter§§
    image: directus/directus:latest
    restart: unless-stopped
    ports:
      - §§portCounter8055§§:8055
    volumes:
      - ./data/uploads:/directus/uploads
      - ./data/extensions:/directus/extensions
    networks:
      - directus_§§label§§_network_§§instanceCounter§§
    depends_on:
      # - directus_§§label§§_cache_§§instanceCounter§§
      - directus_§§label§§_db_§§instanceCounter§§
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "mysql"
      DB_HOST: "directus_§§label§§_db_§§instanceCounter§§"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "§§pwRoot§§"

      CACHE_ENABLED: "false"
      # CACHE_STORE: "redis"
      # CACHE_REDIS: "redis://cache1:6379"

      ADMIN_EMAIL: "§§adminEmail§§"
      ADMIN_PASSWORD: "§§pwAdmin§§"

      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"
      ACCESS_TOKEN_TTL: "20160m"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options/#general)
      # PUBLIC_URL: "§§url§§"

networks:
  directus_§§label§§_network_§§instanceCounter§§:
volumes:
  directus_§§label§§_db_§§instanceCounter§§: